import { createStore } from "vuex";
import { cloneDeep } from "lodash";
import { structure } from "../../src/store/index";
import { getDocs, addDoc } from "firebase/firestore/lite";

jest.mock("firebase/firestore/lite");

getDocs.mockResolvedValue({ docs: [] });

// WARN: id is not generated by uuidv4.
addDoc.mockImplementation(() => Promise.resolve({ id: 1 }));

function factoryStore() {
  const cloneStructure = cloneDeep(structure);
  return createStore(cloneStructure);
}

describe("mutations", () => {
  test("#addContact", () => {
    const store = factoryStore();
    store.commit("addContact", { name: "john" });
    expect(store.state.contacts.all()).toEqual([{ name: "john" }]);
  });
});

describe("store", () => {
  test("contacts is an empty collection", () => {
    const store = factoryStore();
    expect(store.state.contacts.all()).toEqual([]);
  });
});

describe("actions", () => {
  test("addContact", async () => {
    const fakeStore = {
      commit: jest.fn(),
    };
    const fakeContact = { name: "john" };
    await structure.actions.addContact(fakeStore, fakeContact);
    expect(fakeStore.commit).toHaveBeenCalled();
  });
});
